name: CI & Deploy (Monorepo)

on:
  push:
    branches:
      - '*'   # Trigger on any branch

jobs:
  test-build-deploy:
    name: Test, Build & Deploy
    runs-on: ubuntu-latest   # Hosted runner to make sure it triggers

    strategy:
      matrix:
        node-version: [22]  # Node.js version

    steps:
      # 1. Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # 3. Print Environment Secrets (optional)
      - name: Print Env Secrets
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        run: |
          echo "Secrets loaded successfully"

      # 4. Install backend dependencies
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: |
          npm install --global yarn
          yarn install

      # 5. Install frontend dependencies & build
      - name: Install Frontend Dependencies & Build
        working-directory: ./frontend
        run: |
          rm -rf ./build
          yarn install
          yarn run build

      # 6. Run backend tests
      - name: Run Backend Tests
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        working-directory: ./backend
        run: npm test

      # 7. Prepare backend .env
      - name: Setup Backend .env
        run: |
          cd ./backend
          touch .env
          echo "${{ secrets.PROD }}" > .env

      # 8. Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AWS_SERVER_IP }}
          username: ubuntu     # Change to 'ubuntu' if your EC2 user is ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            echo "Deploying backend..."
            cd /home/ec2-user/your-project-directory
            git fetch --all
            git reset --hard $GITHUB_REF_NAME
            npm install
            pm2 restart all
